from __future__ import annotations

from io import BytesIO

from fastapi import Depends, FastAPI, Query
from fastapi.responses import FileResponse

from app.auth import UserContext, get_user_context
from app.config import settings
from app.models import (
    DeleteFileResponse,
    FileInfo,
    FileListResponse,
    GenerateDocxRequest,
    GenerateFileResponse,
    GenerateMarkdownRequest,
    GeneratePptxRequest,
    GenerateXlsxRequest,
    HealthResponse,
)
from app.storage import StoredFile, storage
from app.urls import build_download_url, create_download_token, verify_download_token


def _file_info(stored: StoredFile) -> FileInfo:
    token = create_download_token(file_id=stored.file_id, user_hash=stored.user_hash)

    return FileInfo(
        file_id=stored.file_id,
        filename=stored.filename,
        mime_type=stored.mime_type,
        size_bytes=stored.size_bytes,
        created_at=stored.created_at,
        owner=stored.user_hash,
        download_url=build_download_url(token),
    )


def _ensure_suffix(filename: str | None, title: str, suffix: str) -> str:
    if filename:
        name = filename
    else:
        normalized_title = title.strip().lower().replace(" ", "-")
        name = normalized_title or "document"

    if not name.lower().endswith(suffix):
        name += suffix

    return name


def _generate_docx_bytes(title: str, content: str) -> bytes:
    from docx import Document

    document = Document()
    document.add_heading(title, level=1)

    for paragraph in content.splitlines():
        if paragraph.strip():
            document.add_paragraph(paragraph)
        else:
            document.add_paragraph("")

    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


def _generate_xlsx_bytes(title: str, rows: list[list[str | int | float | bool | None]]) -> bytes:
    from openpyxl import Workbook

    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = "Sheet1"

    if title:
        worksheet.append([title])
        worksheet.append([])

    if rows:
        for row in rows:
            worksheet.append(row)
    else:
        worksheet.append(["No rows provided"])

    buffer = BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def _generate_pptx_bytes(title: str, slides: list[str]) -> bytes:
    from pptx import Presentation

    presentation = Presentation()

    if not slides:
        slides = ["Generated by GenDocTools"]

    for index, slide_text in enumerate(slides):
        layout = presentation.slide_layouts[0] if index == 0 else presentation.slide_layouts[1]
        slide = presentation.slides.add_slide(layout)

        if index == 0:
            slide.shapes.title.text = title
            slide.placeholders[1].text = slide_text
        else:
            slide.shapes.title.text = f"{title} — {index + 1}"
            slide.placeholders[1].text = slide_text

    buffer = BytesIO()
    presentation.save(buffer)
    return buffer.getvalue()


def create_app() -> FastAPI:
    app = FastAPI(
        title="GenDocTools OpenAPI Tool Server",
        version=settings.app_version,
        description=(
            "OpenAI/OpenAPI-compatible document generation tool server for Open WebUI. "
            "This interface is added next to the existing MCP server."
        ),
    )

    @app.get("/health", response_model=HealthResponse, tags=["system"])
    async def health() -> HealthResponse:
        return HealthResponse(version=settings.app_version)

    @app.post(
        "/tools/generate_markdown",
        response_model=GenerateFileResponse,
        tags=["tools"],
        operation_id="generate_markdown",
        summary="Generate a Markdown file",
    )
    async def generate_markdown(
        request: GenerateMarkdownRequest,
        user: UserContext = Depends(get_user_context),
    ) -> GenerateFileResponse:
        filename = _ensure_suffix(request.filename, request.title, ".md")
        markdown = f"# {request.title}\n\n{request.content.strip()}\n"
        data = markdown.encode("utf-8")

        stored = storage.save_bytes(
            user_hash=user.user_hash,
            filename=filename,
            data=data,
            mime_type="text/markdown; charset=utf-8",
        )

        return GenerateFileResponse(
            file=_file_info(stored),
            message="Markdown file generated successfully.",
        )

    @app.post(
        "/tools/generate_docx",
        response_model=GenerateFileResponse,
        tags=["tools"],
        operation_id="generate_docx",
        summary="Generate a DOCX file",
    )
    async def generate_docx(
        request: GenerateDocxRequest,
        user: UserContext = Depends(get_user_context),
    ) -> GenerateFileResponse:
        filename = _ensure_suffix(request.filename, request.title, ".docx")
        data = _generate_docx_bytes(request.title, request.content)

        stored = storage.save_bytes(
            user_hash=user.user_hash,
            filename=filename,
            data=data,
            mime_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        )

        return GenerateFileResponse(
            file=_file_info(stored),
            message="DOCX file generated successfully.",
        )

    @app.post(
        "/tools/generate_xlsx",
        response_model=GenerateFileResponse,
        tags=["tools"],
        operation_id="generate_xlsx",
        summary="Generate an XLSX file",
    )
    async def generate_xlsx(
        request: GenerateXlsxRequest,
        user: UserContext = Depends(get_user_context),
    ) -> GenerateFileResponse:
        filename = _ensure_suffix(request.filename, request.title, ".xlsx")
        data = _generate_xlsx_bytes(request.title, request.rows)

        stored = storage.save_bytes(
            user_hash=user.user_hash,
            filename=filename,
            data=data,
            mime_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        )

        return GenerateFileResponse(
            file=_file_info(stored),
            message="XLSX file generated successfully.",
        )

    @app.post(
        "/tools/generate_pptx",
        response_model=GenerateFileResponse,
        tags=["tools"],
        operation_id="generate_pptx",
        summary="Generate a PPTX file",
    )
    async def generate_pptx(
        request: GeneratePptxRequest,
        user: UserContext = Depends(get_user_context),
    ) -> GenerateFileResponse:
        filename = _ensure_suffix(request.filename, request.title, ".pptx")
        data = _generate_pptx_bytes(request.title, request.slides)

        stored = storage.save_bytes(
            user_hash=user.user_hash,
            filename=filename,
            data=data,
            mime_type="application/vnd.openxmlformats-officedocument.presentationml.presentation",
        )

        return GenerateFileResponse(
            file=_file_info(stored),
            message="PPTX file generated successfully.",
        )

    @app.get(
        "/files",
        response_model=FileListResponse,
        tags=["files"],
        operation_id="list_generated_files",
        summary="List generated files for the current user",
    )
    async def list_files(
        limit: int = Query(default=50, ge=1, le=200),
        user: UserContext = Depends(get_user_context),
    ) -> FileListResponse:
        files = storage.list_files(user_hash=user.user_hash, limit=limit)
        return FileListResponse(files=[_file_info(item) for item in files])

    @app.delete(
        "/files/{file_id}",
        response_model=DeleteFileResponse,
        tags=["files"],
        operation_id="delete_generated_file",
        summary="Delete one generated file for the current user",
    )
    async def delete_file(
        file_id: str,
        user: UserContext = Depends(get_user_context),
    ) -> DeleteFileResponse:
        storage.delete_file(user_hash=user.user_hash, file_id=file_id)
        return DeleteFileResponse(ok=True, file_id=file_id)

    @app.get(
        "/download/{token}",
        tags=["files"],
        include_in_schema=False,
    )
    async def download_file(token: str) -> FileResponse:
        payload = verify_download_token(token)
        stored = storage.get_file(
            user_hash=payload["user_hash"],
            file_id=payload["file_id"],
        )

        return FileResponse(
            path=stored.path,
            filename=stored.filename,
            media_type=stored.mime_type,
        )

    return app
