#!/usr/bin/env bash
set -euo pipefail

BASE_URL="${BASE_URL:-http://localhost:8018}"
USER_ID="${USER_ID:-test-user-1}"

echo "== Health =="
curl -sS "$BASE_URL/health" | jq

echo
echo "== OpenAPI title =="
curl -sS "$BASE_URL/openapi.json" | jq '.info.title'

echo
echo "== Generate Markdown =="
curl -sS -X POST "$BASE_URL/tools/generate_markdown" \
  -H 'Content-Type: application/json' \
  -H "X-OpenWebUI-User-Id: $USER_ID" \
  -d '{
    "title": "Hello GenDocTools",
    "content": "This is a test Markdown document.",
    "filename": "hello-gendoctools.md"
  }' | jq

echo
echo "== Generate DOCX =="
curl -sS -X POST "$BASE_URL/tools/generate_docx" \
  -H 'Content-Type: application/json' \
  -H "X-OpenWebUI-User-Id: $USER_ID" \
  -d '{
    "title": "DOCX Test",
    "content": "Line one\nLine two\nLine three",
    "filename": "docx-test.docx"
  }' | jq

echo
echo "== Generate XLSX =="
curl -sS -X POST "$BASE_URL/tools/generate_xlsx" \
  -H 'Content-Type: application/json' \
  -H "X-OpenWebUI-User-Id: $USER_ID" \
  -d '{
    "title": "XLSX Test",
    "filename": "xlsx-test.xlsx",
    "rows": [
      ["Name", "Value"],
      ["Alpha", 123],
      ["Beta", 456]
    ]
  }' | jq

echo
echo "== Generate PPTX =="
curl -sS -X POST "$BASE_URL/tools/generate_pptx" \
  -H 'Content-Type: application/json' \
  -H "X-OpenWebUI-User-Id: $USER_ID" \
  -d '{
    "title": "PPTX Test",
    "filename": "pptx-test.pptx",
    "slides": [
      "First slide generated by GenDocTools",
      "Second slide",
      "Third slide"
    ]
  }' | jq

echo
echo "== List files =="
curl -sS "$BASE_URL/files" \
  -H "X-OpenWebUI-User-Id: $USER_ID" | jq
